import { expect, test, type Page } from '@playwright/test';
import { Actor, assertNoErrorScreen } from '../src/actors';
import { createAdmin, createClaimableCustomer, prisma } from '../src/fixtures';
import { waitForLatestActivationUrl } from '../src/outbox';
import { primaryRuntime } from '../src/runtime';

/**
 * AUTH-EMAIL-001 — which activation links light the e-mail badge.
 *
 * Two claimable accounts, two links. One is generated by an operator on the
 * customer's admin page and opened as if handed over by hand: the customer
 * gets a password and a session, and both the admin detail and the
 * customer's own settings still say "Doğrulanmadı" for the address. The
 * other is mailed by the platform (the registration claim path) and opened
 * from the outbox: the same screens say "Doğrulandı". The token rows record
 * which was which (`delivery`), and nothing about the phone proof moves.
 */

const PASSWORD = 'E2eYeniSifre123!';

async function activateWithPassword(page: Page): Promise<void> {
  await expect(page.getByRole('heading', { name: 'Şifre belirleyin' })).toBeVisible();
  await page.locator('input[name="password"]').fill(PASSWORD);
  await page.locator('input[name="passwordConfirm"]').fill(PASSWORD);
  await page.getByRole('button', { name: 'Şifreyi Kaydet' }).click();
  await expect(page).not.toHaveURL(/\/activate-customer/);
  await assertNoErrorScreen(page);
}

async function expectProfileEmailBadge(customer: Actor, verified: boolean) {
  await customer.gotoWeb('/account/profile');
  await assertNoErrorScreen(customer.page);
  const badge = customer.page.getByTestId('account-email-verification');
  await expect(badge).toHaveText(verified ? 'Doğrulandı' : 'Doğrulanmadı');
  await expect(badge).toHaveAttribute('data-verified', verified ? 'true' : 'false');
  await expect(customer.page.getByTestId('account-phone-verification')).toHaveText('Doğrulanmadı');
}

async function expectAdminEmailBadge(admin: Actor, customerId: string, verified: boolean) {
  await admin.gotoAdmin(`/customers/${customerId}`);
  await assertNoErrorScreen(admin.page);
  const line = admin.page.getByTestId('customer-email-verification');
  await expect(line).toHaveAttribute('data-verified', verified ? 'true' : 'false');
  await expect(line).toContainText(verified ? 'Doğrulandı' : 'Doğrulanmadı');
  await expect(admin.page.getByTestId('customer-phone-verification')).toHaveAttribute('data-verified', 'false');
}

test.describe('customer activation and the e-mail proof', () => {
  test('an operator-issued link activates the account without proving the address', async ({
    browser,
  }) => {
    const claimable = await createClaimableCustomer('E2E Operatör Linki');
    const adminAccount = await createAdmin();
    const admin = await Actor.open(browser, 'admin', primaryRuntime);
    const customer = await Actor.open(browser, 'customer', primaryRuntime);

    try {
      await admin.loginToAdmin(adminAccount.email, adminAccount.password);
      await admin.gotoAdmin(`/customers/${claimable.id}`);
      await admin.page.getByRole('button', { name: 'Aktivasyon linki oluştur' }).click();
      await expect(admin.page).toHaveURL(/activationUrl=/);
      await assertNoErrorScreen(admin.page);
      const activationUrl = new URL(admin.page.url()).searchParams.get('activationUrl');
      expect(activationUrl, 'the operator is shown the link').toBeTruthy();

      const token = await prisma().customerActivationToken.findFirstOrThrow({
        where: { customerId: claimable.id, usedAt: null },
        select: { delivery: true, createdById: true },
      });
      expect(token).toEqual({ delivery: 'ADMIN_LINK', createdById: adminAccount.id });

      // Handed over by hand — here, straight from the operator's screen.
      await customer.page.goto(activationUrl as string, { waitUntil: 'domcontentloaded' });
      await activateWithPassword(customer.page);

      const row = await prisma().user.findUniqueOrThrow({
        where: { id: claimable.id },
        select: { passwordHash: true, emailVerifiedAt: true, phoneVerifiedAt: true },
      });
      expect(row.passwordHash).not.toBeNull();
      expect(row.emailVerifiedAt).toBeNull();
      expect(row.phoneVerifiedAt).toBeNull();

      await expectProfileEmailBadge(customer, false);
      await expectAdminEmailBadge(admin, claimable.id, false);
      await admin.gotoAdmin(`/customers?q=${encodeURIComponent(claimable.email)}`);
      await expect(admin.page.getByTestId('customer-verification')).toHaveAttribute('data-verified', '');
    } finally {
      await Promise.all([admin.close(), customer.close()]);
    }
  });

  test('a mailed link activates the account and proves the address', async ({ browser }) => {
    const claimable = await createClaimableCustomer('E2E Posta Linki');
    const adminAccount = await createAdmin();
    const admin = await Actor.open(browser, 'admin', primaryRuntime);
    const customer = await Actor.open(browser, 'customer', primaryRuntime);

    try {
      // The registration claim path: the address already belongs to a
      // claimable account, so the platform mails an activation link to it
      // instead of refusing. The response carries no token.
      const claim = await customer.page.request.post(`${primaryRuntime.apiUrl}/auth/register-customer`, {
        data: { name: 'E2E Posta', email: claimable.email, password: PASSWORD },
      });
      expect(claim.status()).toBe(409);
      expect(JSON.stringify(await claim.json())).not.toContain('token=');
      const activationUrl = await waitForLatestActivationUrl(claimable.email);

      const token = await prisma().customerActivationToken.findFirstOrThrow({
        where: { customerId: claimable.id, usedAt: null },
        select: { delivery: true, createdById: true },
      });
      expect(token).toEqual({ delivery: 'EMAIL_DELIVERY', createdById: null });
      // Mailed, not yet followed: no proof yet.
      expect(
        (await prisma().user.findUniqueOrThrow({ where: { id: claimable.id }, select: { emailVerifiedAt: true } }))
          .emailVerifiedAt,
      ).toBeNull();

      await customer.page.goto(activationUrl, { waitUntil: 'domcontentloaded' });
      await activateWithPassword(customer.page);

      const row = await prisma().user.findUniqueOrThrow({
        where: { id: claimable.id },
        select: { passwordHash: true, emailVerifiedAt: true, phoneVerifiedAt: true },
      });
      expect(row.passwordHash).not.toBeNull();
      expect(row.emailVerifiedAt).not.toBeNull();
      expect(row.phoneVerifiedAt).toBeNull();

      await expectProfileEmailBadge(customer, true);
      await admin.loginToAdmin(adminAccount.email, adminAccount.password);
      await expectAdminEmailBadge(admin, claimable.id, true);
    } finally {
      await Promise.all([admin.close(), customer.close()]);
    }
  });
});
