/** Error codes carried in `{ statusCode, error, code, message }` bodies. */
export const REVIEWS_DISABLED_CODE = 'REVIEWS_DISABLED';
export const REQUEST_NOT_COMPLETED_CODE = 'REQUEST_NOT_COMPLETED';
export const MATCH_INCONSISTENT_CODE = 'MATCH_INCONSISTENT';
export const REVIEW_WINDOW_CLOSED_CODE = 'REVIEW_WINDOW_CLOSED';
export const REVIEW_ALREADY_EXISTS_CODE = 'REVIEW_ALREADY_EXISTS';
export const REVIEW_NOT_REPORTABLE_CODE = 'REVIEW_NOT_REPORTABLE';
export const REVIEW_REPORT_ALREADY_EXISTS_CODE = 'REVIEW_REPORT_ALREADY_EXISTS';
export const REVIEW_REPORT_RATE_LIMITED_CODE = 'REVIEW_REPORT_RATE_LIMITED';
export const REVIEW_MODERATION_NOOP_CODE = 'REVIEW_MODERATION_NOOP';
export const NO_OPEN_REVIEW_REPORT_CODE = 'NO_OPEN_REVIEW_REPORT';

export const REVIEW_REPORT_MAX_PER_PROVIDER_PER_DAY = 20;
export const REVIEW_REPORT_NOTE_MAX_LENGTH = 500;
export const REVIEW_MODERATION_NOTE_MAX_LENGTH = 500;
export const REVIEW_LIST_DEFAULT_LIMIT = 20;
export const REVIEW_LIST_MAX_LIMIT = 50;
export const PUBLIC_REVIEW_LIST_MAX_LIMIT = 20;
