import {
  ServiceCategoryKind,
  ServiceCategoryStatus,
  ServiceRequestQuestionSystemField,
  ServiceRequestQuestionType,
} from '@prisma/client';
import type { CategoryDefinition, CategoryWave, QuestionDefinition } from './types';

/**
 * Genişleme dalgası 1 — beş grup ve on beş hizmet, tamamı TASLAK.
 *
 * Bu dalganın tamamı `DRAFT` doğar. Taslak bir kategori adminde görünür,
 * müşteri kataloğunda ve hizmet veren keşfinde görünmez; yayına almak ayrı ve
 * bilinçli bir karardır. Dalga içinde tek bir yönlendirici (ROUTER) yoktur —
 * ilk dalgaya bilerek yalnızca doğrudan hizmetler alınmıştır.
 *
 * Metinler Taktic'e aittir. Araştırma dosyaları yalnızca "bu hizmetin formunda
 * hangi bilgi soruluyor" sorusunun cevabı için okunmuştur; hiçbir kategori adı,
 * tanımı, soru metni veya seçenek etiketi bir kaynaktan kopyalanmamıştır.
 *
 * Sağlık, psikoloji, beslenme, sigorta ve İSG hizmetleri bu dalganın dışındadır.
 */

/**
 * Her hizmetin sonunda duran zorunlu serbest metin.
 *
 * Araştırmadaki on beş formun on beşinde de bir "ihtiyacını anlat" adımı
 * vardır. Taktic'te bunun karşılığı yeni bir soru değil, talebin zaten taşıdığı
 * `description` alanıdır: `DESCRIPTION` sistem bağı o alanı bu kategoride
 * zorunlu kılar ve ona kategoriye özgü bir başlık verir. Böylece aynı metin
 * talep formunda iki kez sorulmaz ve cevap satırına ikinci bir kopya yazılmaz.
 */
function jobDescription(sortOrder: number, label: string, helpText?: string): QuestionDefinition {
  return {
    key: 'is_detayi',
    label,
    helpText,
    type: ServiceRequestQuestionType.TEXTAREA,
    isRequired: true,
    sortOrder,
    systemField: ServiceRequestQuestionSystemField.DESCRIPTION,
  };
}

/**
 * Taşınma tarihi.
 *
 * Araştırma formlarında ayrı bir tarih adımı gözlenmedi; Taktic'te taşınma
 * tarihi zaten talebin `preferredDate` alanıdır ve nakliye işinde tarihsiz bir
 * teklif anlamsızdır. `PREFERRED_DATE` bağı o alanı yalnız bu iki hizmette
 * zorunlu kılar — yeni bir kolon veya yeni bir cevap satırı üretmeden.
 */
function movingDate(sortOrder: number): QuestionDefinition {
  return {
    key: 'tasinma_tarihi',
    label: 'Taşınma için planladığınız tarih',
    helpText: 'Kesinleşmemişse en yakın tahmininizi girin.',
    type: ServiceRequestQuestionType.DATE,
    isRequired: true,
    sortOrder,
    systemField: ServiceRequestQuestionSystemField.PREFERRED_DATE,
  };
}

function option(key: string, label: string) {
  return { key, label };
}

/** m² aralıkları birden çok formda tekrarlandığı için tek yerde durur. */
function areaOptions(values: readonly string[]) {
  return values.map((value) => option(`m2_${value}`, `${value} m²`));
}

const ACCESS_OPTIONS = [
  option('giris_kati', 'Giriş katında'),
  option('zemin_alti', 'Giriş katının altında'),
  option('merdiven_1_3', 'Merdiven — 1 ile 3 kat'),
  option('merdiven_4_ustu', 'Merdiven — 4 kat ve üzeri'),
  option('bina_asansoru', 'Bina asansörü kullanılabilir'),
  option('yuk_asansoru', 'Yük asansörü var'),
  option('moduler_asansor', 'Dış cephe asansörü kurulmalı'),
];

const PACKING_OPTIONS = [
  option('tamami', 'Tüm paketlemeyi hizmet veren yapsın'),
  option('sadece_buyuk', 'Yalnız mobilya ve beyaz eşya paketlensin'),
  option('musteri', 'Paketlemeyi biz yapacağız'),
];

const INSURANCE_OPTIONS = [
  option('yok', 'Sigorta istemiyorum'),
  option('teminat_20000', '20.000 TL teminatlı sigorta'),
  option('teminat_50000', '50.000 TL teminatlı sigorta'),
  option('teminat_100000', '100.000 TL teminatlı sigorta'),
];

const MATERIAL_OPTIONS = [
  option('dahil', 'Malzeme fiyata dahil olsun'),
  option('haric', 'Malzeme hariç, yalnız işçilik'),
];

const groups: CategoryDefinition[] = [
  {
    slug: 'temizlik-ve-hijyen',
    name: 'Temizlik ve Hijyen',
    description: 'Konut ve işyeri temizliği ile özel yüzey bakım hizmetleri.',
    kind: ServiceCategoryKind.GROUP,
    status: ServiceCategoryStatus.DRAFT,
    sortOrder: 100,
    iconKey: 'sparkles',
  },
  {
    slug: 'tasinma-ve-lojistik',
    name: 'Taşınma ve Lojistik',
    description: 'Ev ve işyeri taşıma, depolama ve taşıma iş gücü hizmetleri.',
    kind: ServiceCategoryKind.GROUP,
    status: ServiceCategoryStatus.DRAFT,
    sortOrder: 110,
    iconKey: 'truck',
  },
  {
    slug: 'tadilat-ve-yenileme',
    name: 'Tadilat ve Yenileme',
    description: 'Mekan yenileme, kaplama ve iç uygulama işleri.',
    kind: ServiceCategoryKind.GROUP,
    status: ServiceCategoryStatus.DRAFT,
    sortOrder: 120,
    iconKey: 'brush',
  },
  {
    slug: 'beyaz-esya-teknik-servis',
    name: 'Beyaz Eşya Teknik Servis',
    description: 'Ev aletleri için arıza tespiti, parça değişimi ve bakım.',
    kind: ServiceCategoryKind.GROUP,
    status: ServiceCategoryStatus.DRAFT,
    sortOrder: 130,
    iconKey: 'wrench',
  },
  {
    slug: 'yapi-ve-montaj',
    name: 'Yapı ve Montaj',
    description: 'Sistem kurulumu ve yerinde montaj işleri.',
    kind: ServiceCategoryKind.GROUP,
    status: ServiceCategoryStatus.DRAFT,
    sortOrder: 140,
    iconKey: 'tool',
  },
];

const cleaning: CategoryDefinition[] = [
  {
    slug: 'isyeri-temizlik-hizmeti',
    name: 'İşyeri Temizlik Hizmeti',
    description:
      'Ofis, dükkan ve ortak alanlar için tek seferlik ya da periyodik temizlik.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'temizlik-ve-hijyen',
    offerCreditCost: 3,
    sortOrder: 101,
    iconKey: 'sparkles',
    questions: [
      {
        key: 'temizlik_sikligi',
        label: 'Temizlik hangi sıklıkta yapılsın?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('tek_sefer', 'Tek seferlik'),
          option('iki_haftada_bir', 'İki haftada bir'),
          option('haftada_1', 'Haftada 1 gün'),
          option('haftada_2', 'Haftada 2 gün'),
          option('haftada_3', 'Haftada 3 gün'),
          option('haftada_4', 'Haftada 4 gün'),
          option('haftada_5_ustu', 'Haftada 5 gün ve üzeri'),
        ],
      },
      {
        key: 'alan_m2',
        label: 'Temizlenecek alan yaklaşık kaç m²?',
        helpText: 'En yakın değeri seçmeniz yeterli.',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('m2_30_alti', '30 m² ve altı'),
          ...areaOptions(['50', '80', '100', '150', '200', '250', '300', '400', '500', '800']),
          option('m2_1000_ustu', '1.000 m² ve üzeri'),
        ],
      },
      {
        key: 'dahil_isler',
        label: 'Hizmete hangi işler dahil olsun?',
        helpText: 'Birden fazla seçebilirsiniz.',
        type: ServiceRequestQuestionType.MULTI_SELECT,
        isRequired: true,
        sortOrder: 30,
        options: [
          option('yuzey_silme', 'Masa ve yüzey silme'),
          option('cop', 'Çöp toplama'),
          option('mutfak', 'Mutfak temizliği'),
          option('wc', 'Tuvalet ve banyo temizliği'),
          option('zemin', 'Zemin süpürme ve paspas'),
          option('ic_cam', 'İç cam temizliği'),
          option('dis_cam', 'Dış cam temizliği'),
          option('hali', 'Halı yıkama'),
          option('petek_jaluzi', 'Petek ve jaluzi temizliği'),
          option('detay', 'Dip köşe detay temizliği'),
          option('diger', 'Diğer'),
        ],
      },
      {
        key: 'oda_sayisi',
        label: 'Kaç bağımsız oda veya alan var?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 40,
        options: [
          option('oda_1_2', '1–2 oda'),
          option('oda_3', '3 oda'),
          option('oda_4', '4 oda'),
          option('oda_5', '5 oda'),
          option('oda_6_ustu', '6 oda ve üzeri'),
        ],
      },
      {
        key: 'tuvalet_sayisi',
        label: 'Kaç tuvalet var?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 50,
        options: [
          option('yok', 'Tuvalet yok'),
          option('adet_1', '1'),
          option('adet_2', '2'),
          option('adet_3', '3'),
          option('adet_4_ustu', '4 ve üzeri'),
        ],
      },
      jobDescription(60, 'İşyerinizi ve beklentinizi kısaca anlatın'),
    ],
  },
  {
    slug: 'tadilat-sonrasi-temizlik',
    name: 'Tadilat Sonrası Temizlik',
    description:
      'Tadilat veya inşaat bitiminde toz, boya ve yapıştırıcı kalıntısının temizlenmesi.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'temizlik-ve-hijyen',
    offerCreditCost: 3,
    sortOrder: 102,
    iconKey: 'sparkles',
    questions: [
      {
        key: 'alan_m2',
        label: 'Temizlenecek alan yaklaşık kaç m²?',
        helpText: 'En yakın değeri seçmeniz yeterli.',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          ...areaOptions(['50', '80', '100', '120', '150', '180', '200', '300', '500', '750']),
          option('m2_1000_ustu', '1.000 m² ve üzeri'),
        ],
      },
      {
        key: 'oda_plani',
        label: 'Temizlenecek yer kaç oda + salon?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('plan_1_0', '1+0'),
          option('plan_1_1', '1+1'),
          option('plan_2_1', '2+1'),
          option('plan_3_1', '3+1'),
          option('plan_4_1', '4+1'),
          option('plan_5_1', '5+1'),
          option('plan_6_1_ustu', '6+1 ve üzeri'),
        ],
      },
      {
        key: 'banyo_sayisi',
        label: 'Kaç banyo var?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: [
          option('adet_1', '1'),
          option('adet_2', '2'),
          option('adet_3_ustu', '3 ve üzeri'),
        ],
      },
      {
        key: 'alan_durumu',
        label: 'Alanın bugünkü durumu nedir?',
        helpText: 'Birden fazla seçebilirsiniz.',
        type: ServiceRequestQuestionType.MULTI_SELECT,
        isRequired: true,
        sortOrder: 40,
        options: [
          option('bos', 'Boş, içeride eşya yok'),
          option('boya_siva', 'Boya veya sıva yapıldı'),
          option('insaat_kalintisi', 'İnşaat kalıntısı var'),
          option('etiket', 'Pencerelerden etiket sökülecek'),
          option('diger', 'Diğer'),
        ],
      },
      jobDescription(50, 'Temizlenecek alanı ve beklentinizi kısaca anlatın'),
    ],
  },
  {
    slug: 'yerinde-doseme-yikama',
    name: 'Yerinde Döşeme Yıkama',
    description: 'Koltuk, kanepe, sandalye ve yatağın adreste makineyle yıkanması.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'temizlik-ve-hijyen',
    offerCreditCost: 2,
    sortOrder: 103,
    iconKey: 'drop',
    questions: [
      {
        key: 'tekli_koltuk',
        label: 'Kaç adet tekli koltuk veya berjer var?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('adet_0', '0'),
          option('adet_1', '1'),
          option('adet_2', '2'),
          option('adet_3', '3'),
          option('adet_4', '4'),
          option('adet_5_ustu', '5 ve üzeri'),
        ],
      },
      {
        key: 'kanepe',
        label: 'Kaç adet ikili/üçlü kanepe veya çekyat var?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('adet_0', '0'),
          option('adet_1', '1'),
          option('adet_2', '2'),
          option('adet_3', '3'),
          option('adet_4_ustu', '4 ve üzeri'),
        ],
      },
      {
        key: 'kose_koltuk',
        label: 'Kaç adet köşe koltuk takımı var?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: [
          option('adet_0', '0'),
          option('adet_1', '1'),
          option('adet_2', '2'),
          option('adet_3_ustu', '3 ve üzeri'),
        ],
      },
      {
        key: 'sandalye',
        label: 'Kaç adet sandalye yıkanacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 40,
        options: [
          option('adet_0', '0'),
          option('adet_1_2', '1–2'),
          option('adet_4', '4'),
          option('adet_6', '6'),
          option('adet_8', '8'),
          option('adet_10_ustu', '10 ve üzeri'),
        ],
      },
      {
        key: 'tek_kisilik_yatak',
        label: 'Kaç adet tek kişilik yatak yıkanacak?',
        helpText: 'Eni 130 cm’den dar yataklar tek kişilik sayılır.',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 50,
        options: [
          option('adet_0', '0'),
          option('adet_1', '1'),
          option('adet_2', '2'),
          option('adet_3_ustu', '3 ve üzeri'),
        ],
      },
      {
        key: 'cift_kisilik_yatak',
        label: 'Kaç adet çift kişilik yatak yıkanacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 60,
        options: [
          option('adet_0', '0'),
          option('adet_1', '1'),
          option('adet_2', '2'),
          option('adet_3_ustu', '3 ve üzeri'),
        ],
      },
      jobDescription(70, 'Yıkanacak parçalar ve leke durumu hakkında kısa bir not'),
    ],
  },
  {
    slug: 'bos-daire-temizligi',
    name: 'Boş Daire Temizliği',
    description: 'Taşınma öncesi veya sonrası, eşyasız konutun detaylı temizliği.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'temizlik-ve-hijyen',
    offerCreditCost: 2,
    sortOrder: 104,
    iconKey: 'sparkles',
    questions: [
      {
        key: 'daire_plani',
        label: 'Dairenin planı nedir?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('plan_1_0', '1+0'),
          option('plan_1_1', '1+1'),
          option('plan_2_1', '2+1'),
          option('plan_3_1', '3+1'),
          option('plan_4_1', '4+1'),
          option('plan_5_1', '5+1'),
          option('plan_6_1_ustu', '6+1 ve üzeri'),
        ],
      },
      {
        key: 'banyo_sayisi',
        label: 'Kaç banyo var?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('adet_1', '1'),
          option('adet_2', '2'),
          option('adet_3_ustu', '3 ve üzeri'),
        ],
      },
      {
        key: 'bosalma_sebebi',
        label: 'Daire neden boş?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: [
          option('kiraci_cikti', 'Kiracı çıktı'),
          option('sifir_daire', 'Sıfır daire'),
          option('diger', 'Diğer'),
        ],
      },
      jobDescription(40, 'Dairenin durumu ve beklentiniz hakkında kısa bir not'),
    ],
  },
];

const moving: CategoryDefinition[] = [
  {
    slug: 'evden-eve-tasima',
    name: 'Evden Eve Taşıma',
    description: 'Paketleme, yükleme, nakil ve yerleştirme dahil konut taşıma.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'tasinma-ve-lojistik',
    offerCreditCost: 5,
    sortOrder: 111,
    iconKey: 'truck',
    questions: [
      {
        key: 'oda_sayisi',
        label: 'Kaç odalı ev eşyası taşınacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('plan_1_1', '1+1'),
          option('plan_2_1', '2+1'),
          option('plan_3_1', '3+1'),
          option('plan_4_1', '4+1'),
          option('plan_5_1', '5+1'),
          option('daha_buyuk', 'Daha büyük'),
          option('birkac_esya', 'Yalnızca birkaç parça eşya'),
        ],
      },
      {
        key: 'cikis_erisimi',
        label: 'Eşyalar mevcut adresten nasıl indirilecek?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: ACCESS_OPTIONS,
      },
      {
        key: 'varis_erisimi',
        label: 'Eşyalar yeni adrese nasıl çıkarılacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: ACCESS_OPTIONS,
      },
      {
        key: 'paketleme',
        label: 'Paketleme için yardım gerekiyor mu?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 40,
        options: PACKING_OPTIONS,
      },
      {
        key: 'sigorta',
        label: 'Eşya sigortası ister misiniz?',
        helpText: 'Sigorta, taşıma sırasındaki hasar ve kaza risklerini kapsar.',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 50,
        options: INSURANCE_OPTIONS,
      },
      movingDate(60),
      jobDescription(70, 'Taşınacak eşyalar ve dikkat edilmesi gerekenler'),
    ],
  },
  {
    slug: 'isyeri-tasima',
    name: 'İşyeri Taşıma',
    description: 'Ofis mobilyası, arşiv ve teknik ekipmanın kurumsal nakli.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'tasinma-ve-lojistik',
    offerCreditCost: 5,
    sortOrder: 112,
    iconKey: 'truck',
    questions: [
      {
        key: 'ofis_alani_m2',
        label: 'Mevcut işyeri yaklaşık kaç m²?',
        helpText: 'Eşya miktarını tahmin edebilmek için soruyoruz.',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          ...areaOptions(['30', '50', '80', '100', '120', '150', '200', '300']),
          option('m2_500_ustu', '500 m² ve üzeri'),
          option('birkac_esya', 'Yalnızca birkaç parça eşya'),
        ],
      },
      {
        key: 'paketleme',
        label: 'Paketleme için yardım gerekiyor mu?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: PACKING_OPTIONS,
      },
      {
        key: 'cikis_erisimi',
        label: 'Eşyalar mevcut adresten nasıl indirilecek?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: ACCESS_OPTIONS,
      },
      {
        key: 'varis_erisimi',
        label: 'Eşyalar yeni adrese nasıl çıkarılacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 40,
        options: ACCESS_OPTIONS,
      },
      {
        key: 'sigorta',
        label: 'Eşya sigortası ister misiniz?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 50,
        options: INSURANCE_OPTIONS,
      },
      movingDate(60),
      jobDescription(70, 'Taşınacak ekipman ve dikkat edilmesi gerekenler'),
    ],
  },
  {
    slug: 'esya-depolama',
    name: 'Eşya Depolama',
    description: 'Süreli veya süresiz eşya saklama ve depo alanı.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'tasinma-ve-lojistik',
    offerCreditCost: 3,
    sortOrder: 113,
    iconKey: 'box',
    questions: [
      {
        key: 'esya_miktari',
        label: 'Ne kadar eşya depolanacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('birkac_parca', 'Birkaç parça eşya'),
          option('plan_1_1', '1+1 ev eşyası'),
          option('plan_2_1', '2+1 ev eşyası'),
          option('plan_3_1', '3+1 ev eşyası'),
          option('plan_4_1', '4+1 ev eşyası'),
          option('daha_fazla', 'Daha fazlası'),
        ],
      },
      {
        key: 'depolama_suresi',
        label: 'Eşyalar ne kadar süre kalacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('bir_ay_alti', '1 ay veya daha az'),
          option('uc_ay', '3 ay'),
          option('alti_ay', '6 ay'),
          option('bir_yil', '1 yıl'),
          option('iki_yil_ustu', '2 yıl ve üzeri'),
        ],
      },
      {
        key: 'nakliye_dahil',
        label: 'Eşyaların depoya taşınması hizmete dahil olsun mu?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: [
          option('evet', 'Evet, hizmet veren alsın'),
          option('hayir', 'Hayır, depoya biz götüreceğiz'),
        ],
      },
      {
        key: 'paketleme',
        label: 'Eşyalar paketlensin mi?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 40,
        options: [
          option('tamami', 'Tüm eşyalar paketlensin'),
          option('sadece_buyuk', 'Yalnız büyük eşyalar paketlensin'),
          option('musteri', 'Paketlemeyi biz yapacağız'),
          option('paketsiz', 'Paketlenmeden depolansın'),
        ],
      },
      jobDescription(50, 'Depolanacak eşyalar hakkında kısa bir not'),
    ],
  },
  {
    slug: 'asansorlu-tasima',
    name: 'Asansörlü Taşıma',
    description: 'Dış cephe mobil asansörüyle yüksek katlara eşya indirme ve çıkarma.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'tasinma-ve-lojistik',
    offerCreditCost: 4,
    sortOrder: 114,
    iconKey: 'truck',
    questions: [
      {
        key: 'oda_sayisi',
        label: 'Kaç odalı ev eşyası taşınacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('plan_1_1', '1+1'),
          option('plan_2_1', '2+1'),
          option('plan_3_1', '3+1'),
          option('plan_4_1', '4+1'),
          option('plan_5_1', '5+1'),
          option('daha_buyuk', 'Daha büyük'),
          option('birkac_esya', 'Yalnızca birkaç parça eşya'),
        ],
      },
      {
        key: 'cikis_erisimi',
        label: 'Eşyalar mevcut adresten nasıl indirilecek?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: ACCESS_OPTIONS,
      },
      {
        key: 'varis_erisimi',
        label: 'Eşyalar yeni adrese nasıl çıkarılacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: ACCESS_OPTIONS,
      },
      {
        key: 'paketleme',
        label: 'Paketleme için yardım gerekiyor mu?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 40,
        options: PACKING_OPTIONS,
      },
      {
        key: 'sigorta',
        label: 'Eşya sigortası ister misiniz?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 50,
        options: INSURANCE_OPTIONS,
      },
      jobDescription(60, 'Kat, cephe ve eşya durumu hakkında kısa bir not'),
    ],
  },
  {
    slug: 'hamaliye-hizmeti',
    name: 'Hamaliye Hizmeti',
    description: 'Yalnızca yükleme, boşaltma ve taşıma iş gücü.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'tasinma-ve-lojistik',
    offerCreditCost: 2,
    sortOrder: 115,
    iconKey: 'box',
    questions: [
      {
        key: 'buyuk_esya_adedi',
        label: 'Kaç adet büyük eşya taşınacak?',
        helpText: 'Yatak, buzdolabı, çamaşır makinesi, masa gibi parçalar.',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('adet_0', '0'),
          option('adet_1_2', '1–2'),
          option('adet_3_5', '3–5'),
          option('adet_6_10', '6–10'),
          option('adet_11_20', '11–20'),
          option('adet_21_ustu', '21 ve üzeri'),
        ],
      },
      {
        key: 'koli_adedi',
        label: 'Kaç koli veya hurç taşınacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('adet_0', '0'),
          option('adet_1_5', '1–5'),
          option('adet_6_10', '6–10'),
          option('adet_11_20', '11–20'),
          option('adet_21_40', '21–40'),
          option('adet_41_ustu', '41 ve üzeri'),
        ],
      },
      {
        key: 'alinacak_kat',
        label: 'Eşyalar kaçıncı kattan alınacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: [
          option('kat_0', 'Giriş katı'),
          option('kat_1_3', '1–3. kat'),
          option('kat_4_6', '4–6. kat'),
          option('kat_7_ustu', '7. kat ve üzeri'),
        ],
      },
      {
        key: 'birakilacak_kat',
        label: 'Eşyalar kaçıncı kata çıkarılacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 40,
        options: [
          option('kat_0', 'Giriş katı'),
          option('kat_1_3', '1–3. kat'),
          option('kat_4_6', '4–6. kat'),
          option('kat_7_ustu', '7. kat ve üzeri'),
        ],
      },
      {
        key: 'sure',
        label: 'Yaklaşık kaç saat yardım gerekiyor?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 50,
        options: [
          option('saat_1', '1 saat'),
          option('saat_2', '2 saat'),
          option('saat_3', '3 saat'),
          option('saat_4', '4 saat'),
          option('saat_5_6', '5–6 saat'),
          option('tum_gun', 'Tüm gün'),
          option('bilinmiyor', 'Emin değilim'),
        ],
      },
      {
        key: 'kisi_sayisi',
        label: 'Kaç kişiye ihtiyacınız var?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 60,
        options: [
          option('kisi_1', '1 kişi'),
          option('kisi_2', '2 kişi'),
          option('kisi_3', '3 kişi'),
          option('kisi_4', '4 kişi'),
          option('kisi_5_ustu', '5 kişi ve üzeri'),
          option('bilinmiyor', 'Emin değilim'),
        ],
      },
      {
        key: 'ek_hizmetler',
        label: 'Ek hizmete ihtiyacınız var mı?',
        helpText: 'Birden fazla seçebilir veya boş bırakabilirsiniz.',
        type: ServiceRequestQuestionType.MULTI_SELECT,
        isRequired: false,
        sortOrder: 70,
        options: [
          option('demontaj', 'Mobilya sökümü'),
          option('montaj', 'Mobilya kurulumu'),
          option('buyuk_paketleme', 'Büyük eşyaların paketlenmesi'),
          option('kolileme', 'Küçük eşyaların kolilenmesi'),
          option('diger', 'Diğer'),
        ],
      },
      jobDescription(80, 'İşin yeri ve zamanı hakkında kısa bir not'),
    ],
  },
];

const renovation: CategoryDefinition[] = [
  {
    slug: 'banyo-yenileme',
    name: 'Banyo Yenileme',
    description: 'Seramik, tesisat, vitrifiye ve dolap işlerini kapsayan banyo tadilatı.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'tadilat-ve-yenileme',
    offerCreditCost: 6,
    sortOrder: 121,
    iconKey: 'brush',
    questions: [
      {
        key: 'tadilat_tipi',
        label: 'Hangi tip banyo işine ihtiyacınız var?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('komple', 'Komple banyo yenileme'),
          option('fayans', 'Fayans veya seramik döşeme'),
          option('dusakabin', 'Duşakabin işleri'),
          option('dolap', 'Banyo dolabı'),
          option('tesisat', 'Su tesisatı ve kaçak'),
          option('vitrifiye', 'Klozet ve lavabo işleri'),
          option('tavan', 'Tavan kaplama'),
          option('diger', 'Diğer'),
        ],
      },
      {
        /*
         * Koşullu soru: yalnız "komple yenileme" seçildiğinde görünür.
         *
         * Tek bir kalem için (örneğin yalnız duşakabin) bu listeyi sormak
         * müşteriye anlamsız bir adım ekler; komple yenilemede ise işin kapsamı
         * tam olarak bu listedir. Kural sunucuda da doğrulanır: bu soru
         * görünmüyorken gönderilen bir cevap 400 döner.
         */
        key: 'yapilacak_isler',
        label: 'Komple yenilemede hangi işler yapılacak?',
        helpText: 'Birden fazla seçebilirsiniz.',
        type: ServiceRequestQuestionType.MULTI_SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('fayans', 'Fayans döşeme'),
          option('dusakabin', 'Duşakabin'),
          option('klozet', 'Klozet'),
          option('lavabo', 'Lavabo'),
          option('tesisat', 'Tesisat'),
          option('dolap', 'Dolap'),
          option('tavan', 'Tavan'),
          option('kuvet', 'Küvet'),
          option('kapi', 'Kapı'),
          option('tezgah', 'Tezgah'),
          option('diger', 'Diğer'),
        ],
        conditions: [{ sourceQuestionKey: 'tadilat_tipi', expectedValues: ['komple'] }],
      },
      {
        key: 'alan_m2',
        label: 'Banyo yaklaşık kaç m²?',
        helpText: 'En yakın değeri seçmeniz yeterli.',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: [
          ...areaOptions(['5', '10', '15', '20', '25', '30', '40']),
          option('m2_50_ustu', '50 m² ve üzeri'),
        ],
      },
      {
        key: 'malzeme_dahil',
        label: 'Fiyata malzeme dahil olsun mu?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 40,
        options: MATERIAL_OPTIONS,
      },
      jobDescription(50, 'Banyonun bugünkü durumu ve beklentiniz'),
    ],
  },
  {
    slug: 'asma-tavan-uygulamasi',
    name: 'Asma Tavan Uygulaması',
    description: 'Alçıpan asma tavan tasarımı ve montajı.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'tadilat-ve-yenileme',
    offerCreditCost: 4,
    sortOrder: 122,
    iconKey: 'tool',
    questions: [
      {
        key: 'alan_m2',
        label: 'Toplam kaç m² asma tavan yapılacak?',
        helpText: 'En yakın değeri seçmeniz yeterli.',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          ...areaOptions(['5', '10', '15', '20', '25', '30', '40', '50', '60', '80', '100', '150', '200', '300']),
          option('m2_500_ustu', '500 m² ve üzeri'),
        ],
      },
      {
        key: 'uygulama_alani',
        label: 'Hangi bölümlere uygulanacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('tum_ev', 'Evin tamamı'),
          option('salon', 'Yalnız salon'),
          option('mutfak', 'Yalnız mutfak'),
          option('banyo', 'Yalnız banyo'),
          option('koridor', 'Yalnız koridor'),
          option('salon_mutfak', 'Salon ve mutfak'),
          option('tek_oda', 'Tek bir oda'),
          option('iki_uc_oda', '2–3 oda'),
          option('teras', 'Teras'),
          option('diger', 'Diğer'),
        ],
      },
      {
        key: 'ek_hizmetler',
        label: 'Ek olarak hangi işler yapılacak?',
        helpText: 'Birden fazla seçebilir veya boş bırakabilirsiniz.',
        type: ServiceRequestQuestionType.MULTI_SELECT,
        isRequired: false,
        sortOrder: 30,
        options: [
          option('aydinlatma', 'Aydınlatma (spot, LED)'),
          option('boya', 'Boya'),
          option('kartonpiyer', 'Kartonpiyer'),
          option('eski_tavan_sokumu', 'Eski tavanın sökülmesi'),
          option('yalitim', 'Isı, ses veya su yalıtımı'),
          option('diger', 'Diğer'),
        ],
      },
      {
        key: 'malzeme_dahil',
        label: 'Fiyata malzeme dahil olsun mu?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 40,
        options: MATERIAL_OPTIONS,
      },
      jobDescription(50, 'Tavan yüksekliği ve beklentiniz hakkında kısa bir not'),
    ],
  },
  {
    slug: 'banyo-seramik-kaplama',
    name: 'Banyo Seramik Kaplama',
    description: 'Banyo duvar ve zemininin fayans veya seramikle kaplanması.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'tadilat-ve-yenileme',
    offerCreditCost: 4,
    sortOrder: 123,
    iconKey: 'brush',
    questions: [
      {
        key: 'alan_m2',
        label: 'Kaplanacak alan yaklaşık kaç m²?',
        helpText: 'En yakın değeri seçmeniz yeterli.',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          ...areaOptions(['3', '5', '10', '15', '20', '25', '30', '40', '50', '60', '80', '100']),
          option('m2_150_ustu', '150 m² ve üzeri'),
        ],
      },
      {
        key: 'kaplama_alanlari',
        label: 'Hangi yüzeyler kaplanacak?',
        helpText: 'Birden fazla seçebilirsiniz.',
        type: ServiceRequestQuestionType.MULTI_SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('banyo_duvar', 'Banyo duvarı'),
          option('banyo_zemin', 'Banyo zemini'),
          option('diger_duvar', 'Diğer duvarlar'),
          option('diger_zemin', 'Diğer zeminler'),
        ],
      },
      {
        key: 'malzeme_dahil',
        label: 'Fiyata malzeme dahil olsun mu?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: MATERIAL_OPTIONS,
      },
      {
        key: 'ek_isler',
        label: 'Kaplama dışında yapılacak iş var mı?',
        helpText: 'Birden fazla seçebilir veya boş bırakabilirsiniz.',
        type: ServiceRequestQuestionType.MULTI_SELECT,
        isRequired: false,
        sortOrder: 40,
        options: [
          option('dusakabin', 'Duşakabin'),
          option('tesisat', 'Su tesisatı'),
          option('sap', 'Şap atımı'),
          option('diger', 'Diğer'),
        ],
      },
      {
        key: 'mevcut_kaplama',
        label: 'Sökülecek mevcut kaplama var mı?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 50,
        options: [
          option('sokulecek', 'Evet, mevcut kaplama sökülecek'),
          option('gerek_yok', 'Hayır, söküme gerek yok'),
        ],
      },
      jobDescription(60, 'Yüzeyin bugünkü durumu hakkında kısa bir not'),
    ],
  },
];

const appliances: CategoryDefinition[] = [
  {
    slug: 'camasir-makinesi-onarimi',
    name: 'Çamaşır Makinesi Onarımı',
    description: 'Çamaşır makinesi arıza tespiti, parça değişimi ve bakımı.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'beyaz-esya-teknik-servis',
    offerCreditCost: 2,
    sortOrder: 131,
    iconKey: 'wrench',
    questions: [
      {
        key: 'ariza',
        label: 'Makinede ne oluyor?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('calismiyor', 'Hiç çalışmıyor'),
          option('hata_kodu', 'Hata kodu veriyor'),
          option('su_almiyor', 'Su almıyor'),
          option('su_kaciriyor', 'Su kaçırıyor'),
          option('sikma_yapmiyor', 'Sıkma yapmıyor'),
          option('tambur_donmuyor', 'Tambur dönmüyor'),
          option('ses_yapiyor', 'Ses yapıyor veya gürültülü çalışıyor'),
          option('kapak', 'Kapak arızası'),
          option('parca_degisimi', 'Parça değişimi gerekiyor'),
          option('bakim', 'Periyodik bakım'),
          option('diger', 'Diğer'),
        ],
      },
      {
        key: 'marka',
        label: 'Makinenin markası nedir?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('arcelik', 'Arçelik'),
          option('beko', 'Beko'),
          option('bosch', 'Bosch'),
          option('siemens', 'Siemens'),
          option('samsung', 'Samsung'),
          option('lg', 'LG'),
          option('vestel', 'Vestel'),
          option('ariston', 'Ariston'),
          option('diger', 'Diğer'),
        ],
      },
      jobDescription(30, 'Arızayı ne zamandır yaşadığınızı kısaca anlatın'),
    ],
  },
  {
    slug: 'bulasik-makinesi-onarimi',
    name: 'Bulaşık Makinesi Onarımı',
    description: 'Bulaşık makinesi arıza tespiti ve onarımı.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'beyaz-esya-teknik-servis',
    offerCreditCost: 2,
    sortOrder: 132,
    iconKey: 'wrench',
    questions: [
      {
        key: 'ariza',
        label: 'Makinede ne oluyor?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('calismiyor', 'Hiç çalışmıyor'),
          option('hata_kodu', 'Hata kodu veriyor'),
          option('su_almiyor', 'Su almıyor'),
          option('su_bosaltmiyor', 'Suyu boşaltmıyor'),
          option('su_kaciriyor', 'Su kaçırıyor'),
          option('isitmiyor', 'Suyu ısıtmıyor'),
          option('yikamaya_gecmiyor', 'Su alıyor ama yıkamaya geçmiyor'),
          option('kapak', 'Kapak arızası'),
          option('parca_degisimi', 'Parça değişimi gerekiyor'),
          option('diger', 'Diğer'),
        ],
      },
      {
        key: 'marka',
        label: 'Makinenin markası nedir?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('arcelik', 'Arçelik'),
          option('beko', 'Beko'),
          option('bosch', 'Bosch'),
          option('siemens', 'Siemens'),
          option('samsung', 'Samsung'),
          option('lg', 'LG'),
          option('vestel', 'Vestel'),
          option('profilo', 'Profilo'),
          option('ariston', 'Ariston'),
          option('diger', 'Diğer'),
        ],
      },
      jobDescription(30, 'Arızayı ne zamandır yaşadığınızı kısaca anlatın'),
    ],
  },
];

const installation: CategoryDefinition[] = [
  {
    slug: 'guvenlik-kamerasi-kurulumu',
    name: 'Güvenlik Kamerası Kurulumu',
    description: 'Kamera, kayıt cihazı ve kablolamanın kurulumu.',
    kind: ServiceCategoryKind.LEAF,
    status: ServiceCategoryStatus.DRAFT,
    parentSlug: 'yapi-ve-montaj',
    offerCreditCost: 3,
    sortOrder: 141,
    iconKey: 'bolt',
    questions: [
      {
        key: 'kamera_adedi',
        label: 'Kaç adet kamera kurulacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 10,
        options: [
          option('adet_1', '1'),
          option('adet_2', '2'),
          option('adet_3', '3'),
          option('adet_4', '4'),
          option('adet_5_6', '5–6'),
          option('adet_7_8', '7–8'),
          option('adet_9_ustu', '9 ve üzeri'),
        ],
      },
      {
        key: 'sistem_tipi',
        label: 'Hangi sistem kurulacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 20,
        options: [
          option('ip_poe', 'IP kamera (PoE / NVR)'),
          option('analog_dvr', 'Analog kamera (AHD / DVR)'),
          option('wifi', 'Kablosuz (Wi-Fi) kamera'),
          option('bilinmiyor', 'Emin değilim, öneri istiyorum'),
        ],
      },
      {
        key: 'kurulum_yeri',
        label: 'Kurulum nereye yapılacak?',
        type: ServiceRequestQuestionType.SELECT,
        isRequired: true,
        sortOrder: 30,
        options: [
          option('konut', 'Ev veya daire'),
          option('apartman', 'Apartman veya site'),
          option('dukkan', 'Dükkan'),
          option('ofis', 'Ofis'),
          option('depo', 'Depo veya fabrika'),
          option('diger', 'Diğer'),
        ],
      },
      jobDescription(40, 'Kurulum yapılacak alan hakkında kısa bir not'),
    ],
  },
];

export const WAVE_1: CategoryWave = {
  name: 'wave-1-draft',
  // Groups first: a leaf names its parent by slug, and the importer creates
  // categories in the order they appear.
  categories: [...groups, ...cleaning, ...moving, ...renovation, ...appliances, ...installation],
};
