export const REPORT_MAX_PER_PROVIDER_PER_DAY = 20;
export const REPORT_NOTE_MAX_LENGTH = 500;
export const REPORT_ALREADY_EXISTS_CODE = 'REPORT_ALREADY_EXISTS';
export const REPORT_RATE_LIMITED_CODE = 'REPORT_RATE_LIMITED';
