'use server';

import { revalidatePath } from 'next/cache';
import { apiUrl, readApiMessage } from '../api-base';
import { cookies } from 'next/headers';

/**
 * Sending a message, as a server action.
 *
 * The composer is a real form: it works before JavaScript has loaded and it
 * works if JavaScript never loads. The client component around it enhances the
 * experience — polling, an optimistic clear — but the send itself is this
 * action, so a browser with scripting disabled is not locked out of the one
 * feature that lets two matched people talk.
 *
 * Every refusal comes back as a value rather than an exception. A rate limit,
 * an empty body and a closed conversation are things the person needs to read
 * on the screen they are on, not the generic error boundary.
 */

export type SendMessageState = {
  status: 'idle' | 'sent' | 'error';
  /** Shown verbatim; the API writes these in Turkish for exactly this purpose. */
  message?: string;
  /** Kept so a refused send does not also lose what the person typed. */
  draft?: string;
};

export async function sendMessageAction(
  _previous: SendMessageState,
  formData: FormData,
): Promise<SendMessageState> {
  const threadId = readString(formData, 'threadId');
  const body = readString(formData, 'body');
  // Generated by the form, not here: a key minted server-side would be new on
  // every submission and would protect nothing.
  const clientToken = readString(formData, 'clientToken');

  if (!threadId) {
    return { status: 'error', message: 'Bu konuşma bulunamadı.', draft: body };
  }

  if (!body.trim()) {
    return { status: 'error', message: 'Mesaj boş olamaz.', draft: '' };
  }

  const cookieHeader = (await cookies()).toString();

  let response: Response;
  try {
    response = await fetch(
      `${apiUrl}/messages/threads/${encodeURIComponent(threadId)}/messages`,
      {
        method: 'POST',
        headers: { 'content-type': 'application/json', cookie: cookieHeader },
        body: JSON.stringify({ body, ...(clientToken ? { clientToken } : {}) }),
        cache: 'no-store',
      },
    );
  } catch {
    return {
      status: 'error',
      message: 'Mesaj gönderilemedi. Bağlantınızı kontrol edip tekrar deneyin.',
      draft: body,
    };
  }

  if (!response.ok) {
    return {
      status: 'error',
      message: (await readApiMessage(response)) ?? refusalFor(response.status),
      draft: body,
    };
  }

  // The thread screen re-reads its history on the server, so the sent message
  // is on the page after this action even with scripting off.
  revalidatePath(`/mesajlar/${threadId}`);
  revalidatePath('/mesajlar');

  return { status: 'sent' };
}

/**
 * A sentence for a status the API did not write one for.
 *
 * Only ever a fallback — the API's own message is preferred, because it is the
 * one that knows which rule was broken.
 */
function refusalFor(status: number): string {
  if (status === 429) {
    return 'Çok hızlı mesaj gönderiyorsunuz. Lütfen biraz bekleyip tekrar deneyin.';
  }

  if (status === 401) {
    return 'Oturumunuz sona ermiş olabilir. Lütfen tekrar giriş yapın.';
  }

  if (status === 403 || status === 404) {
    return 'Bu konuşmaya artık erişiminiz yok.';
  }

  return 'Mesaj gönderilemedi. Lütfen tekrar deneyin.';
}

function readString(formData: FormData, key: string): string {
  const value = formData.get(key);
  return typeof value === 'string' ? value : '';
}
